### ISSUE TITLE
Integración con Travis y contenido del README

### ISSUE THREAD

**Issue by lauramcastro** [elias-garcia/vvs#1]
Recordad que para cumplir los requisitos de la primera semana, debéis enlazar el repositorio con Travis-CI, que debe ser capaz de ejecutar correctamente la construcción del proyecto, e incluir el badge en el README (punto 3 del enunciado). Además el README debe contener una breve descripción del proyecto (punto 4 del enunciado).

**Comment by lauramcastro** [comment]
Ahora que lo habéis solucionado, podéis cerrar esta issue! :+1: 

Antes de cerrarla (en realidad, en el momento que os ponéis a atenderla), deberíais asignarle una etiqueta y también una persona responsable (`Assignee`).

**Comment by elias-garcia** [comment]
Integración con Travis completada y archivo README.md modificado.
